name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PROJECT_FOLDER: './DoHome'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ${{env.PROJECT_FOLDER}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.PROJECT_FOLDER}}
      run: dotnet build --no-restore --configuration Release
